before:
  hooks:
    - go mod download
#monorepo:
#  tag_prefix: cmd/builder/
#  dir: cmd/builder
builds:
  - flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/windmeup/opentelemetry-collector/cmd/builder/internal.version={{.Version}} -X github.com/windmeup/opentelemetry-collector/cmd/builder/internal.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
    ignore:
      - goos: windows
        goarch: arm64
    binary: ocb
release:
  github:
    owner: windmeup
    name: opentelemetry-collector
  header: |
    ### Images and binaries here: https://github.com/windmeup/opentelemetry-collector-releases/releases/tag/{{ .Tag }}
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
